# Generated by Django 5.1.2 on 2024-10-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
