# Generated by Django 5.1.2 on 2024-10-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
