# Generated by Django 5.1.2 on 2024-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_rename_assets_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='followers',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
