# Generated by Django 5.1.2 on 2024-10-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='followers',
        ),
    ]
