# Generated by Django 5.1.2 on 2024-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='asset',
        ),
    ]
