# Generated by Django 5.1.2 on 2024-10-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_user_portfolio_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default='carteira de <django.db.models.fields.related.OneToOneField>', max_length=100),
        ),
    ]
