# Generated by Django 5.1.2 on 2024-10-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='username',
            new_name='user',
        ),
    ]
