# Generated by Django 5.1.2 on 2024-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_portfolioasset_ticker_portfolioasset_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='followers',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
